function getScenario() {
    return [
        { label: "prologue" },
        { type: "message1", image: "test.png", name: "解説", text: "ぼくはたぬき。どこにでもいるふつうのたぬき。\n今日は友達のひよこ、ねこと山の中をさんさくしている。" },
        { type: "message1", image: "prologue1.png", name: "解説", text: "しばらく歩いていると、ふいに パーン パパーン と音がした。" },
        { type: "message1", image: "prologue1.png", name: "たぬき、ひよこ、ねこ", text: "「？」「？」「？」\nみんなで首をかしげた。" },
        { type: "message1", image: "prologue1.png", name: "ひよこ", text: "「なんだろう？」" },
        { type: "message1", image: "prologue1.png", name: "ねこ", text: "「おばけ！？」" },
        { type: "message1", image: "prologue1.png", name: "たぬき", text: "「音がしたほうに行ってみる？」" },
        { type: "message1", image: "prologue2.png", name: "解説", text: "みんな怖そうだけれど、行くことにした。" },
        { type: "message1", image: "prologue3.png", name: "解説", text: "しばらく歩くと、小屋が見えた。" },
        { type: "message1", image: "prologue3.png", name: "たぬき", text: "（あれは...？）" },
        { type: "message1", image: "prologue3.png", name: "解説", text: "何かが動いた！\n\nまた動いた。" },
        { type: "message1", image: "prologue2.png", name: "解説", text: "好奇心がおさえられなくて、近づいてみた。" },
        { type: "message1", image: "prologue4.png", name: "たぬき、ひよこ、ねこ", text: "（あっ！）\n\n誰か小屋から出てきた！\nねこが何かにとびついた！" },
        { type: "message1", image: "black.png", name: "？？", text: "パーン！！" },
        { type: "message1", image: "black.png", name: "たぬき", text: "「うっ！」" },
        { type: "choice", image: "black.png", name: "タイトルへ", text: "", choices: [{ text: "タイトルへ", jump: "htmlTitle" }] },
        { label: "startGame" },
        { type: "message1", image: "black.png", name: "たぬき", text: "「んん？」「あっ！」\n（ここはどこ？ぼくはどうしたの？）\n（ひよことねこはどこ？）\n\n あ 思い出した！" },
        { type: "message1", image: "black.png", name: "たぬき", text: "（何か変なものに当たって...　\nあの時ねこが何かに飛びついたとき... \nそういえばここは、なんにもない。まさか、天国に行く道？）" },
        { type: "message1", image: "black.png", name: "たぬき", text: "（そうだ！！ぼくは死んでしまったんだ！）" },
        { type: "message1", image: "black.png", name: "たぬき", text: "「ん？」" },
        { type: "message1", image: "tv.gif", name: "解説", text: "コンピューターが現れた！\nさっき死ぬときの映像だ。" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よく見ると...\nこれは銃だ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "そういえばあの時、誰かの悲鳴と銃の玉がぶつかる感触がしたな。" },
        { type: "message1", image: "test.png", name: "たぬき", text: "そのあとの映像を見ると..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "（ひよことねこが笑っている！？）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（ぼくのこと殺そうと、たくらんでいたんだ！！）" },
        { type: "choice", image: "test.png", name: "たぬき", text: "一生呪ってやろうかな？ でも一生友達だよって言った親友だし...", choices: [{ text: "呪う", jump: "fcurse" }, { text: "呪わない", jump: "fncurse" }] },
        { label: "fncurse" },
        { type: "message1", image: "test.png", name: "たぬき", text: "呪わないことにした。" },
        { type: "message1", image: "test.png", name: "たぬき", text: "次に他の人の動画を見せられた。\nどうやら同じような死に方をした人の動画だ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「んん？」\nこの人は呪ったのか..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "また違う人の動画を見せられた。\n今見た動画の全員、殺した人を呪ってる！" },
        { type: "choice", image: "test.png", name: "たぬき", text: "この動画を見せるということは、呪えと言っているようなものだ。よし！やっぱり呪うぞ！", choices: [{ text: "呪う", jump: "fcurse" }, { text: "呪う", jump: "fcurse" }] },
        { label: "fcurse" },
        { type: "message1", image: "test.png", name: "たぬき", text: "҉パ҉ァ҉ァ҉" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「眠い...」\nめちゃくちゃ眠い..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "（どうしよう？なんか温かい！？\n光につつまれている感じがする...？）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（どんどん眠気におそわれていく...\n違う場所に飛ばされる感じがする...\nいやな予感が...）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "..." },
        { type: "message1", image: "black.png", name: "たぬき", text: "さあ、たぬきの行き先は..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "「んん？」\n" },
        { type: "message1", image: "test.png", name: "たぬき", text: "また他のところに来たぞ！？\nまたモニターがある..." },
        { type: "choice", image: "test.png", name: "たぬき", text: "また呪うか呪わないか選択しろと！？\nよし、今回は...", choices: [{ text: "呪う", jump: "curse" }, { text: "呪わない", jump: "ncurse" }] },
        { label: "ncurse" },
        { type: "message1", image: "test.png", name: "？？", text: "ヒューン　ヒューン" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「？」（なにこれ？）" },
        { type: "message1", image: "test.png", name: "解説", text: "風を切る音、ノコギリの音..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "（まさか殺される！？）\n「ギャーーーーーー！！」" },
        { type: "message1", image: "test.png", name: "解説", text: "声がボワンボワーンとひびく。" },
        { type: "message1", image: "test.png", name: "？？", text: "「トンッ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（ん？なんだ？）高層ビルみたいなところから落ちたと思うけど、なんの痛さも感じない。どうしてだろう？" },
        { type: "message1", image: "test.png", name: "たぬき", text: "見上げると、上のほうにぽつんと灰色の明かり。" },
        { type: "choice", image: "test.png", name: "たぬき", text: "あんな高いところから落ちたんだ。\nはしごがついてる！この先は通路だ！進みたいけどノコギリの音が...どうしよう！？", choices: [{ text: "戻る", jump: "hback" }, { text: "進む", jump: "pg" }] },
        { label: "hback" },
        { type: "message1", image: "test.png", name: "たぬき", text: "あの高さまで登るのか...こわいけど...決めたんだから登らなきゃ！じゃないと始まらない！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "いきおいにまかせて手をかけた。すると、体がどんどん上に行く。" },
        { type: "message1", image: "test.png", name: "解説", text: "〚　解説　〛たぬきは足がないから、はしごを登るのは結構キツイのだ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "ちょうど半分くらいかな？と思ったところで手を止めた。下を見ると、　\n「高ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー！！！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "げんじつとうひ\n\n私は何も見ていないそう私は何も見ていない\nそう私は何も関係ないすべては神さまだが何だが悪いのだそうだ！！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "上を見ると、いくらなんでもありすぎでしょ！！何回見てもはしごはしごはしごはしごはしごはしｇ\nはぁー見てるだけでつかれるー💦" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よしっがんばるぞ！！また手をかけると、体がどんどん上へ進んでいく。" },
        //↑まだ終わっていない
        { label: "pg" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よしっ進むぞ！！でも...こわいしなー...でも決めた！進む！コケがたくさんある...クモの巣もある！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ヒッ」クモが目の前にぶら下がってる！！" },
        { type: "message1", image: "test.png", name: "クモ", text: "「ヒヒヒ、怖いんだな、ただし先に進むといいことがあるぜ！てか、こんな怖いという人はじめてみたわい！！」「ハハハハハ」" },
        { type: "cimg", image: "test.png", image2: "real.png", key:"r", name: "たぬき", text: "何あのクモ、めちゃくちゃムカつくんだけど╬　╬　╬" },
        { type: "message1", image: "test.png", name: "たぬき", text: "でもいいことがあるって言ってたな。まあ進んでみるか！どんどんいくと、ドアがいきなり出現した！天国へって書いてある！もう迷わない！！行くよ！" },
        { label: "curse" },
        { type: "message1", image: "test.png", name: "解説", text: "呪うを選択した！\n目の前にドアが現れた！？" },
        { type: "message1", image: "test.png", name: "たぬき", text: "行き先は...　じごく！？" },
        { type: "message1", image: "test.png", name: "たぬき", text: "どどどどどどどどうしよう！？\nでも、まわりにはなにもないし、「呪う」を選択しちゃったからしょうがないよね？" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし！思いっきり入ってみよう！！" },
        { type: "message1", image: "black.png", name: "解説", text: "さあ、たぬきはどうなる！？" },
        { type: "message1", image: "test.png", name: "風の音", text: "༄　ヒュー" },
        { type: "message1", image: "test.png", name: "たぬき", text: "えっ　ここは...\n\nじごくだぁーーーーーーーーー！！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "えんま大王が審査を行っている！！" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "「おいっ　そこのたぬき！！」" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "「お前はこのままじごくに残るか天国へ行くかどっちがいいか！？」" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "「答えろ！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "ひぃーーー💦\n天国に行きたいけどいやな予感がするから、じごくに残ろう！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「じっじごくに残ります」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（あっ）やばい声が小さくなりすぎた！" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "「あー！？」\n「なんだって！？聞こえねえぞ！！」" },
        { type: "choice", image: "test.png", name: "たぬき", text: "もっもう一回！？　（天国に行きたいなぁ...）なにこの気持ち！？もうっ！決めたんだ！！\nでっでも行きたいかも...", choices: [{ text: "天国に行く", jump: "over1" }, { text: "地獄に残る", jump: "jigoku" }] },
        { label: "over1" },
        { type: "message1", image: "oni.png", name: "鬼たち", text: "「ヴァッカモーーーン！！」" },
        { type: "message1", image: "oni.png", name: "たぬき", text: "「！？」\nいつからいたのか、鬼が5匹、ぼくのまわりをかこんでいる！" },
        { type: "message1", image: "oni.png", name: "たぬき", text: "そして、こん棒と銃で殺そうとしているんだ...　今度こそ死んでしまう！！\n「やっやめて！！」" },
        { type: "message1", image: "oni.png", name: "鬼たち", text: "「問答無用！！」" },
        { type: "gameOver", image: "black.png", name: "？？", text: "パーン！！" },
        { label: "jigoku" },
        { type: "choice", image: "test.png", name: "なぞの生物", text: "「君は、他の皆と違って少し、頭がよさそうだな！！\nそれだけにおしい...　ここからは、じごくを冒険してもらう。全てのじごくをクリアしたら、天国へいけ！！」", choices: [{ text: "始める", jump: "jigoku1" }] },
        { label: "jigoku1" },
        { type: "message1", image: "test.png", name: "なぞの生物", text: "「最初は、針山じごくだ。さあ、ルール説明は次だ」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下", text: "「ルール説明で頭がこんがらないように、気を付けるんだな！！」「じゃあ始める！！」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下", text: "「あーしてこーして　まあいい！！はりやまじごくをクリアしたら矢印がさす方向に進んで　\n一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一\n一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（はっはや！？最初しか聞き取れなかった...）" },
        { type: "message1", image: "test.png", name: "えんま大王の手下", text: "「いいな？？」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（え、何？一切わからないけハイって答えるしかないよね？）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ハ、ハイッ！」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下", text: "「じゃ、ファイト！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（え、もうやっていいってこと？\nえーいどうでもいい　やるぞ！）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ん？」\nげたがある！これをはけってことか..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし、じゃあ改めてやるぞ！" },
        { type: "message1", image: "test.png", name: "？？", text: "ボキッボキボキボキ" },
        { type: "choice", image: "test.png", name: "たぬき", text: "何この音？まさかげたが壊れる音！！？\nもう半分くらいまで来たけど引き返そうかな？", choices: [{ text: "引き返す", jump: "hariyamagoal" }, { text: "進む", jump: "over2" }] },
        { label: "over2" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ギャアアアアアアアアアアア...___________________________！！」" },
        { type: "gameOver", image: "black.png", name: "解説", text: "背中に強いしょうげきが走ったと同時にたぬきの意識はなくなった。その時たぬきは何が起こったのか確信した。" },
        { label: "hariyamagoal" },
        { type: "message1", image: "test.png", name: "たぬき", text: "引き返して正解だった。\n「ん？」げたのとなりにせおえるカゴが置いてあるぞ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "これの中にげたを入れてせおうのか！これで進めるぞ！" },
        { type: "message1", image: "test.png", name: "？？", text: "バキッ" },
        { type: "message1", image: "test.png", name: "たぬき", text: "折れそう！でも新しいげたを取り出せば！" },
        { type: "message1", image: "white.png", name: "解説", text: "これを何回かくり返し..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "最後にジャンプしてゴール！" },
        { type: "choice", image: "test.png", name: "えんま大王の手下", text: "「なかなかやるじゃないか」「次へ行け」", choices: [{ text: "次へ行く", jump: "huttou" }] },
        { label: "huttou" },
        { type: "message1", image: "test.png", name: "えんま大王の手下2", text: "「今回はふっとうじごくだ」「そこのでかいなべの中に入って五分間もちこたえればいい\nとちゅうで熱くなったら出ていいが、もし出てしまったら...針山じごくからやり直せ！！」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下2", text: "「ルール説明はここまでだ。あとこのコインをくれてやる」「そこの列にならべ！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（なんかさっきの鬼よりこわすぎるんですけど）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "まあ列にならぶか...ならんでと...ふーん一回に十人入るのか！それにしても出たら一からか...\nまあがんばるぞ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし！！ぼくの番だ！相変わらずじごくの鬼はらんぼうだな...（まあ例外もいるけど...）" },
        { type: "message1", image: "test.png", name: "？？", text: "ドンッ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（キャーー）声にならない声！！あっつーーーーーー！！！！" },
        { type: "choice", image: "test.png", name: "たぬき", text: "こんなに熱いの知らないよ！！助けて！もう出たい！でも一からだし...", choices: [{ text: "でる", jump: "loop" }, { text: "泳ぐ", jump: "swim" }, { text: "でない", jump: "over3" }] },
        { label: "over3" },
        { type: "message1", image: "test.png", name: "たぬき", text: "クッもう無理だ...\nぼくは、ここで死んでしまうんだ..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "選択を違うのにすればよかった..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "今ごろ後悔しても...おそい...か..." },
        { type: "gameOver", image: "test.png", name: "たぬき", text: "たぬきの意識はなくなった..." },
        { label: "loop" },
        { type: "message1", image: "test.png", name: "たぬき", text: "出るぞ！でもどうやって出るんだ？\n鬼さんに聞いてみるか！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「おっおおおおにさんどどどどうやってでるんですか？」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下3", text: "「ん？」「あぁでるんだな☺\nそこのはしごで登って、矢印の方向に進むと、針山じごくに行ける！！がんばれよ！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（？やさしっ！？）（この鬼好きかも！！こんなにじごくにきた人にやさしい人はいない！？　まさかかくしごとがあるのかも？）\n（まぁいいや！）\n「よしっ」はしご登ってやるぞ！" },
        { type: "choice", image: "test.png", name: "たぬき", text: "　", choices: [{ text: "矢印についていく", jump: "jigoku1" }] },
        { label: "swim" },
        { type: "message1", image: "test.png", name: "たぬき", text: "クッ　ももう無理だでも　お泳ぐぞ！！\n犬かきだぁーー！！バチャバチャバチャバチャ　意外と熱くないぞ！！" },
        { type: "message1", image: "test.png", name: "えんま大王の手下3", text: "「おいおい君」「もう五分たったよ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（えっ！？）「よっしゃーーーーーーーーー！！」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下3", text: "「うっさい！」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下3", text: "「まあがんばったな！次もがんばれよ　はしごを登って矢印の方向へ行けばいい」" },

    ];
};

