function getScenario() {
    return [
        { label: "prologue" },
        { type: "message1", image: "test.png", name: "解説", text: "ぼくはたぬき。どこにでもいるふつうのたぬき。\n今日は友達のひよこ、ねこと山の中をさんさくしている。" },
        { type: "message1", image: "prologue1.png", name: "解説", text: "しばらく歩いていると、ふいに パーン パパーン と音がした。" },
        { type: "message1", image: "prologue1.png", name: "たぬき、ひよこ、ねこ", text: "「？」「？」「？」\nみんなで首をかしげた。" },
        { type: "message1", image: "prologue1.png", name: "ひよこ", text: "「なんだろう？」" },
        { type: "message1", image: "prologue1.png", name: "ねこ", text: "「おばけ！？」" },
        { type: "message1", image: "prologue1.png", name: "たぬき", text: "「音がしたほうに行ってみる？」" },
        { type: "message1", image: "prologue2.png", name: "解説", text: "みんな怖そうだけれど、行くことにした。" },
        { type: "message1", image: "prologue3.png", name: "解説", text: "しばらく歩くと、小屋が見えた。" },
        { type: "message1", image: "prologue3.png", name: "たぬき", text: "（あれは...？）" },
        { type: "message1", image: "prologue3.png", name: "解説", text: "何かが動いた！\n\nまた動いた。" },
        { type: "message1", image: "prologue2.png", name: "解説", text: "好奇心がおさえられなくて、近づいてみた。" },
        { type: "message1", image: "prologue4.png", name: "たぬき、ひよこ、ねこ", text: "（あっ！）\n\n誰か小屋から出てきた！\nねこが何かにとびついた！" },
        { type: "message1", image: "black.png", name: "？？", text: "パーン！！" },
        { type: "message1", image: "black.png", name: "たぬき", text: "「うっ！」" },
        { type: "choice", image: "black.png", name: "タイトルへ", text: "　", choices: [{ text: "タイトルへ", jump: "htmlTitle" }] },
        { label: "startGame" },
        { type: "message1", image: "black.png", name: "たぬき", text: "「んん？」「あっ！」\n（ここはどこ？ぼくはどうしたの？）\n（ひよことねこはどこ？）\n\n あ 思い出した！" },
        { type: "message1", image: "black.png", name: "たぬき", text: "（何か変なものに当たって...　\nあの時ねこが何かに飛びついたとき... \nそういえばここは、なんにもない。まさか、天国に行く道？）" },
        { type: "message1", image: "black.png", name: "たぬき", text: "（そうだ！！ぼくは死んでしまったんだ！）" },
        { type: "message1", image: "black.png", name: "たぬき", text: "「ん？」" },
        { type: "message1", image: "tv.gif", name: "解説", text: "コンピューターが現れた！\nさっき死ぬときの映像だ。" },
        { type: "message1", image: "1-1.png", name: "たぬき", text: "よく見ると...\nこれは銃だ！" },
        { type: "message1", image: "1-1.png", name: "たぬき", text: "そういえばあの時、誰かの悲鳴と銃の玉がぶつかる感触がしたな。" },
        { type: "message1", image: "white.png", name: "たぬき", text: "そのあとの映像を見ると..." },
        { type: "message1", image: "1-2.png", name: "たぬき", text: "（ひよことねこが笑っている！？）" },
        { type: "message1", image: "1-3.gif", name: "たぬき", text: "（ぼくのこと殺そうと、たくらんでいたんだ！！）　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　" },
        { type: "choice", image: "1-4.png", name: "たぬき", text: "一生呪ってやろうかな？ でも一生友達だよって言った親友だし...", choices: [{ text: "呪う", jump: "fcurse" }, { text: "呪わない", jump: "fncurse" }] },
        { label: "fncurse" },
        { type: "message1", image: "white.png", name: "たぬき", text: "呪わないことにした。" },
        { type: "message1", image: "2-1.png", name: "たぬき", text: "次に他の人の動画を見せられた。\nどうやら同じような死に方をした人の動画だ！" },
        { type: "message1", image: "2-2.png", name: "たぬき", text: "「んん？」\nこの人は呪ったのか..." },
        { type: "message1", image: "2-3.png", name: "たぬき", text: "また違う人の動画を見せられた。\n今見た動画の全員、殺した人を呪ってる！" },
        { type: "choice", image: "test.png", name: "たぬき", text: "この動画を見せるということは、呪えと言っているようなものだ。よし！やっぱり呪うぞ！", choices: [{ text: "呪う", jump: "fcurse" }, { text: "呪う", jump: "fcurse" }] },
        { label: "fcurse" },
        { type: "message1", image: "test.png", name: "たぬき", text: "҉パ҉ァ҉ァ҉" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「眠い...」\nめちゃくちゃ眠い..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "（どうしよう？なんか温かい！？\n光につつまれている感じがする...？）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（どんどん眠気におそわれていく...\n違う場所に飛ばされる感じがする...\nいやな予感が...）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "..." },
        { type: "message1", image: "black.png", name: "たぬき", text: "さあ、たぬきの行き先は..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "「んん？」\n" },
        { type: "message1", image: "test.png", name: "たぬき", text: "また他のところに来たぞ！？\nまたモニターがある..." },
        { type: "choice", image: "test.png", name: "たぬき", text: "また呪うか呪わないか選択しろと！？\nよし、今回は...", choices: [{ text: "呪う", jump: "curse" }, { text: "呪わない", jump: "ncurse" }] },
        { label: "ncurse" },
        { type: "message1", image: "test.png", name: "？？", text: "ヒューン　ヒューン" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「？」（なにこれ？）" },
        { type: "message1", image: "test.png", name: "解説", text: "風を切る音、ノコギリの音..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "（まさか殺される！？）\n「ギャーーーーーー！！」" },
        { type: "message1", image: "test.png", name: "解説", text: "声がボワンボワーンとひびく。" },
        { type: "message1", image: "test.png", name: "？？", text: "「トンッ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（ん？なんだ？）高層ビルみたいなところから落ちたと思うけど、なんの痛さも感じない。どうしてだろう？" },
        { type: "message1", image: "test.png", name: "たぬき", text: "見上げると、上のほうにぽつんと灰色の明かり。" },
        { label: "32hasigo" },
        { type: "choice", image: "test.png", name: "たぬき", text: "あんな高いところから落ちたんだ。\nはしごがついてる！この先は通路だ！進みたいけどノコギリの音が...どうしよう！？", choices: [{ text: "戻る", jump: "hback" }, { text: "進む", jump: "pg" }] },
        { label: "hback" },
        { type: "message1", image: "test.png", name: "たぬき", text: "あの高さまで登るのか...こわいけど...決めたんだから登らなきゃ！じゃないと始まらない！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "いきおいにまかせて手をかけた。すると、体がどんどん上に行く。" },
        { type: "message1", image: "test.png", name: "解説", text: "〚　解説　〛たぬきは足がないから、はしごを登るのは結構キツイのだ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "ちょうど半分くらいかな？と思ったところで手を止めた。下を見ると、　\n「高ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー！！！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "げんじつとうひ\n\n私は何も見ていないそう私は何も見ていない\nそう私は何も関係ないすべては神さまだが何だが悪いのだそうだ！！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "上を見ると、いくらなんでもありすぎでしょ！！何回見てもはしごはしごはしごはしごはしごはしｇ\nはぁー見てるだけでつかれるー💦" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よしっがんばるぞ！！また手をかけると、体がどんどん上へ進んでいく。" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（てっ手がつかれてきた...）\n（あっもう少し！）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「つ、ついたー！　頂上だーーーー！」" },
        { type: "choice", image: "test.png", name: "たぬき", text: "ってあれ？\n上から風が吹いてくる...\n引き返したいけどこのまま地上に出たいし...", choices: [{ text: "引き返す", jump: "hasigoloop" }, { text: "残る", jump: "hasigoover" }] },
        { label: "hasigoloop" },
        { type: "choice", image: "test.png", name: "たぬき", text: "引き返して正解だった。よし、このまま戻って...", choices: [{ text: "戻る", jump: "32hasigo" }] },
        { label: "hasigoover" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（手がつかれてきた...これじゃ落ちるのも時間の問題だ...\nあっ片手が...）" },
        { type: "gameOver", image: "test.png", name: "たぬき", text: "「あっ　ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ」" },
        { label: "pg" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よしっ進むぞ！！でも...こわいしなー...でも決めた！進む！でもコケがたくさんある...クモの巣もある！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ヒッ」クモが目の前にぶら下がってる！！" },
        { type: "message1", image: "test.png", name: "クモ", text: "「ヒヒヒ、怖いんだな、ただし先に進むといいことがあるぜ！てか、こんな怖いという人はじめてみたわい！！」「ハハハハハ」" },
        { type: "cimg", image: "test.png", image2: "real.png", key: "r", name: "たぬき", text: "何あのクモ、めちゃくちゃムカつくんだけど💢💢💢" },
        { type: "message1", image: "test.png", name: "たぬき", text: "でもいいことがあるって言ってたな。まあ進んでみるか！どんどんいくと、ドアがいきなり出現した！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "[style='border:2px solid #000;padding:6px;']天国へ]って書いてある！もう迷わない！！行くよ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "ワッ！？　ヒューン　ズテッ" },
        { type: "message1", image: "test.png", name: "たぬき", text: "いってぇーー。もう💢なんなのココ？" },
        { type: "message1", image: "test.png", name: "？？？", text: "「あらぁ　新人くんねぇ」「ごきげんよう」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「だっだれ？」" },
        { type: "message1", image: "test.png", name: "？？？", text: "「あっそうだったわ」「自己紹介してなかったわね。自称：上品マダムよ。年齢は非公開よ。」" },
        { type: "message1", image: "test.png", name: "（自称）上品マダム", text: "「[style='font-weight:bold']わたくしの死の原因は、交通事故ですわ！]」「[style='font-size:15px']もう50こえて...]あ、何でもないわ！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（いやそこ　はりきっていうところじゃない...。）[style='font-size:15px']（あと何か聞こえたような...）]" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「あっ、あと、本名はタヌコよ！！」[style='font-size:15px']たぬき（意外と名前ジミ...。）]" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「これからあなたには天国とこの世のはざまを旅してもらうわ。詳しくはこの『マダムのとびら』をオープンしてから教えるわ。手下A！！スタンバイよろしく！」" },
        { type: "message1", image: "test.png", name: "？？？と？？？", text: "「こんにちは！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（！？）「だっだれ！？」" },
        { type: "message1", image: "test.png", name: "？？？と？？？", text: "「あ、[style='text-decoration:line-through']自称]上品マダムに仕える手下Aと...　手下Bっす！ちーっす！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "お、おお...？" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「ちょっとB！！初対面の方に対して失礼なふるまいを...！！」" },
        { type: "message1", image: "test.png", name: "手下B", text: "「あ、すみません、気を取り直してルールを説明いたします。」" },
        { type: "message1", image: "test.png", name: "手下A", text: "「あなたは天国...とはいいきれませんがこの地で3つの試練をクリアしていく必要があります。」" },
        { type: "message1", image: "test.png", name: "手下B", text: "「３つですがけっこうハードです。どのような試練が出るかはチャレンジしてから。」\n「質問はありますか？」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "どうしよう...あ、そうだ！　「あの......」" },
        { type: "message1", image: "test.png", name: "手下A", text: "「はい？」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「クリアしたらどうなるんですか？」" },
        { type: "message1", image: "test.png", name: "手下A", text: "「・・・。」" },
        { type: "message1", image: "test.png", name: "鐘", text: "＜＜キーンコーンカーンコーン＞＞" },
        { type: "message1", image: "test.png", name: "手下A", text: "「あ、最初の試練が始まります。急いで！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "え？質問の答えは？まあ行くか...　なんの試練だろう？" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし！席についたぞ。。。" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "＜＜最初の試練はクイズです。＞＞" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "＜＜第一問：上品マダムの本名は？\n机の上の紙に記入お願いいたします。＞＞" },
        { type: "choice", image: "test.png", name: "たぬき", text: "（ん－なんだっけなー...）", choices: [{ text: "タヌコ", jump: "tanuko" }, { text: "タヌミ", jump: "tanumi" }] },
        { label: "tanuko" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし！タヌコにした！\nタヌコっと...机が高い..." },
        { type: "message1", image: "test.png", name: "？？", text: "ピンポーン" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "＜＜正解おめでとうございます＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "ええっ！？書いただけで？すげえ～！" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "＜＜たぬきには、次の試練に進む資格が与えられます＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（ポワーン）なにかワープできそうな円が現れた！この中に入ろう！ピューン" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「おほほほほ　正解おめでとうございます　お祝いの印に一杯やりませんか？」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（なっなにを飲むんだろ？まぁなんでもいいや...）\n「えっいいんですか？」" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「ええ、ぜひ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「お願いします！！」" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「A、B準備お願い☆」" },
        { type: "message1", image: "test.png", name: "手下A, B", text: "「ハイッ奥様」（さささ　ガシャーン　バリーン　ささささ　ガシャーン）" },
        { type: "message1", image: "test.png", name: "手下A, B", text: "「準備完了！！」「ではカンパーイ！」" },
        { type: "message1", image: "test.png", name: "一同", text: "「イェーイ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（ゴクッ）なんかみんなの視線がすごいな...。まあいいか。\nん？なんか意識が...遠のいて...いく......（バタッ）" },
        { type: "message1", image: "black.png", name: "⍰", text: "　" },
        { type: "message1", image: "test.png", name: "たぬき", text: "ん？" },
        { type: "message1", image: "test.png", name: "？？？", text: "「あら起きたみたいねーー。」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（だ、だれ？この人...だれ？）" },
        { type: "message1", image: "test.png", name: "？？？", text: "「まあ当然ね」「ワインの中に薬を入れるなんて我ながら良いアイデアね～♡」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（どゆこと？）" },
        { type: "choice", image: "test.png", name: "？？？", text: "この子は良い実験対象になりそう♡", choices: [{ text: "この人は誰？", jump: "kiokusousitu" }] },
        { label: "tanumi" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし！タヌミにしてみたぞ！\nタヌミっと...机高っ..." },
        { type: "message1", image: "test.png", name: "？？", text: "[style='color:red;']ブッブー]" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "＜＜たぬき不正解　よって地縛霊に変換します＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "やばい！（ピコーン）何か出てきた！？体が吸い込まれていくー　ぼくどうなるの！？" },
        { type: "message1", image: "test.png", name: "？？", text: "ヒューン ドン" },
        { type: "message1", image: "test.png", name: "たぬき", text: "なっなんだ上のほうにポツンとあかりが！あんなとこから落ちてきたんだ..." },
        { type: "message1", image: "test.png", name: "？？？", text: "そこのお前早くドアに入れ！" },
        { type: "message1", image: "test.png", name: "？？", text: "ドン" },
        { type: "message1", image: "test.png", name: "たぬき", text: "わーーー..." },
        { type: "message1", image: "black.png", name: "たぬき", text: "ん？" },
        { type: "message1", image: "test.png", name: "？？？", text: "「あら起きたみたいねーー。」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（だ、だれ？この人...だれ？）" },
        { type: "message1", image: "test.png", name: "？？？", text: "「まあ当然ね」「気絶させるなんて我ながら良いアイデアねー♡」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（どゆこと？）" },
        { type: "choice", image: "test.png", name: "？？？", text: "この子は良い実験対象になりそう♡", choices: [{ text: "この人は誰？", jump: "kiokusousitu" }] },
        { label: "kiokusousitu" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（この人は本当に何のことを言っているんだ？）" },
        { type: "message1", image: "test.png", name: "？？？", text: "「クイズを出して記憶喪失にする...　今まで何人もの人々が失敗してきた...」" },
        { type: "message1", image: "test.png", name: "？？？", text: "「でもあなたには期待するわ。不正解だったらもちろんバツがあるけどね♡」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（？？っていうことはぼくは今記憶喪失？だからこのババア...あ、訂正。この人のことはわからないのか！）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（じゃあクイズに挑戦すればいいんだな！）" },
        { type: "message1", image: "test.png", name: "？？？", text: "「あ、いっとくけど私相手の心がわかるからね♡　だから今君が...ババアって私のことを言ったのもわかるからね♡」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（えええー？？？や、やばっ！？）" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「ま、そういうことでいざクイズへgo！」" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「手下A, B準備よろしく！！」" },
        { type: "message1", image: "test.png", name: "手下A, B", text: "「はい！奥様」" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「あっ、あと今から出す問題はさっきの試練の続きですわ。まあクイズの第二問ということよ♡　言ってもわからいと思うけど...　まっ、始めるわよ♡」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "？？？なんかよく分かんないこと言ってるけど、よしっ！気合を入れて頑張るぞ！オオー！？" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「＜＜第二問＞＞」" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "＜＜上品マダムのお歳は？そこに机にある紙に記入してください。質問はありますか？＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（えっ、質問いいの？じゃあ答えとかいける？）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ハイッ！」" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「何ですか？」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「上品マダムのお歳は、なんですか？」" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「ピーピー　答えを聞いてはいけません」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（や、やっぱじゃあ他のを...）\n「あっあの...上品マダムとはだれのことでしょうか？」（まさかさっきのババア...あやべっ）" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「知りませんでしたか？そうでした。あなたは記憶喪失でしたね。まあ後々わかることです。おっとあまり長くなりすぎたので質問タイム終了です。問題に答えてください。」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（え？なんも分からない！！どどどどうしよう！？）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（えーい　ここは運でいくしかない！）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（よっよし　えーっとまず上品マダムは誰なのかわからないからそこから考えないと。たぶんさっき「手下A, B準備よろしく！」って言ってたババアだとおもうんだけど...うん絶対そうだ！マダムだし...上品だし...ババアだし...　あやべ　まあいいか）" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "＜＜残り一分＞＞" },
        { type: "choice", image: "test.png", name: "たぬき", text: "（え？せいげん時間なんてあるの！？）まあまああのババアなら、あっ訂正あの人なら、40とか50とか、いってんじゃない？[style='font-size:15px']もしかしたら60...]選択肢は40,45,50か...さぁどれだ！？", choices: [{ text: "40", jump: "choice40" }, { text: "45", jump: "choice45" }, { text: "50", jump: "choice50" }] },
        { label: "choice40" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "＜＜残り、30秒＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし、この机の紙に40っと...高い..." },
        { type: "message1", image: "test.png", name: "モニターの声", text: "＜＜残り、5秒, 4, 3, 2, 1＞＞" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "＜＜クイズ第二問終了します。答え合わせをします＞＞" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「答え合わせ中...」" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「たぬきの結果は...　[style='color:red;']ブッブー]」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「えーー？？？？？？？」\nちちち違うの？" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「たぬき不正解　よって地縛霊に変換します」" },
        { type: "message1", image: "test.png", name: "？？", text: "ヒューン ドン" },
        { type: "message1", image: "test.png", name: "たぬき", text: "なっなんだ上のほうにポツンとあかりが！あんなとこから落ちてきたんだ..." },
        { type: "message1", image: "test.png", name: "？？？", text: "そこのお前早くドアに入れ！" },
        { type: "message1", image: "test.png", name: "？？", text: "ドン" },
        { type: "choice", image: "test.png", name: "たぬき", text: "わーーー...", choices: [{ text: "さっきの人は誰？", jump: "overjibakurei" }] },
        { label: "choice45" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "＜＜残り、30秒＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし、45歳に決めたぞ！！紙に書いて...机高っ！！45っと...OK!!" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "＜＜残り、5秒, 4, 3, 2, 1＞＞" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "＜＜クイズ第二問終了します。答え合わせをします＞＞" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「答え合わせ中...」" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「たぬきの結果は...　[style='color:red;']ブッブー]」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「えーー？？？？？？？」\nちちち違うの？" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「たぬき不正解　よって地縛霊に変換します」" },
        { type: "message1", image: "test.png", name: "？？", text: "ヒューン ドン" },
        { type: "message1", image: "test.png", name: "たぬき", text: "なっなんだ上のほうにポツンとあかりが！あんなとこから落ちてきたんだ..." },
        { type: "message1", image: "test.png", name: "？？？", text: "そこのお前早くドアに入れ！" },
        { type: "message1", image: "test.png", name: "？？", text: "ドン" },
        { type: "choice", image: "test.png", name: "たぬき", text: "わーーー...", choices: [{ text: "さっきの人は誰？", jump: "overjibakurei" }] },
        { label: "overjibakurei" },
        { type: "message1", image: "test.png", name: "？？？", text: "「おいそこのお前！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（んんんんん？ぼ、ぼくは？そういえばなんか黒い人に押されて、変なドアに入ったんだ、、、。でこいつあっ訂正この人は？）" },
        { type: "message1", image: "test.png", name: "？？？", text: "「オレは地縛霊の霊長だ！！オレのことは霊長と呼べ１！いいな？　ま、そういうのはおいといて、こういうのは聞いても意味ないからな！！」" },
        { type: "message1", image: "test.png", name: "霊長", text: "「ってことでお前の名前は？」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（霊長こわっ💦）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「たたたたたたぬきです！！」" },
        { type: "message1", image: "test.png", name: "霊長", text: "「そうか、ではこれから死んでもらう。」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「えええっ？」" },
        { type: "message1", image: "test.png", name: "霊長", text: "「じゃあな、たたたたたたたぬき！！」「[style='font-weight:bold;font-size:40px;']パーン]」" },
        { type: "gameOver", image: "test.png", name: "解説", text: "そこでたぬきの意識はなくなった。黒い霊長はいつの間にか銃を出していたのだ。" },
        { label: "choice50" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "＜＜残り、30秒＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "や、やば！！まあ、あと記入するだけだから。50っと" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "＜＜残り、5秒, 4, 3, 2, 1＞＞" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "＜＜クイズ第二問終了します。答え合わせをします＞＞" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「答え合わせ中...」" },
        { type: "message1", image: "test.png", name: "モニターの声", text: "「[style='color:#7d7d05;']ピンポンピンポンピンポーン]」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「イエーイやったやった！　正解だぁ！」" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「おめでとうございます。ココマデこれたのはあなたが初めてだわ！」「もう初老か...トホホ...」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「まっまじ！とそこじゃなくて、今妙にココマデのところがカタコトになっていたような...。というかこのババア...あ　この方の歳は50歳なのか...」" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「まあ今回も一杯やりましょうか」\n「手下A, B準備お願い！」" },
        { type: "message1", image: "test.png", name: "上品マダムとたぬき", text: "「カンパーイ！！イエーイ！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（ゴクッ）なんかみんなの視線がすごいな...。まあいいか。\nん？なんか意識が...遠のいて...いく......（バタッ）" },
        { type: "message1", image: "black.png", name: "⍰", text: "　" },
        { type: "message1", image: "test.png", name: "？？？", text: "「はーい！おはようさーん！！」「起きたみたいね！君を記憶喪失にしたのは、私よ！！まあわかってると思うけど。」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（あーあ！このババアめやりやがったか...！！）" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「ま　それはおいといて...第一試練クリアよ！次の試練は...なんだっけ？」「手下A, B！次の試練は？」" },
        { type: "message1", image: "test.png", name: "手下A, B", text: "「はい、奥様、次の試練は頭の良さ対決でございます！」" },
        { type: "message1", image: "test.png", name: "上品マダム", text: "「あーそうだったわ！じゃあそこのマダムのとびらに入ってね　よろしく頼むわ！あと手下A, B準備よろしく(・ω<)☆」" },
        { type: "message1", image: "test.png", name: "手下A, B", text: "「はい、奥様」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（っとぼくはこの○○のとびら[style='font-size:20px;']ババアのとびら？だっけ？]に入らなきゃ）" },
        { type: "message1", image: "test.png", name: "手下A, B", text: "「ピーピー　席についてくださーい！！」" },
        { type: "message1", image: "test.png", name: "手下B", text: "「たぬき様　2番の席におつきください」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ハハハイ」" },
        { type: "message1", image: "test.png", name: "手下A", text: "「ではルール説明をいたします。ルールは簡単　前のモニターに出てくるクイズなどの答えを、そこのボタンを押して言ってもらいます！当ててもらってから答えてください！10人いるので5番目から最後までにボタンを押した人は、脱落です！一番最後に残った人が、次の試練に進めます！」" },
        { type: "message1", image: "test.png", name: "手下B", text: "「いっとくけどど他の参加者はすべてアンドロイドです！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "ええええええええええええ？そそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそそれはないでしょ　アンドロイドに勝てっこないよ！！💦" },
        { type: "message1", image: "test.png", name: "手下A, B", text: "「では始めますので席についてくださーい！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "えっとえーっと　二番のいすは...あ！これか。ちょっと緊張するけど、がんばるぞ！！アンドロイドに勝つぞ！！" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "「ピンポーン」たぬき「ん？アナウンスだ」" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "「それでは始めさせていただきます！！」\n「第1問！デレーン」" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "「『discombobulate』の意味は？」ピンポンピンポン　たぬき「はや！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「えっととりあえずボタンを押して...」「ピポン」「OK!!」 " },
        { type: "message1", image: "test.png", name: "アナウンス", text: "「アンドロイド0006様　答えをそこの紙に記入してください！アンドロイド0003、0004様、たぬき様もご記入お願いします！！他の人に見られないよう10秒でお願いします！！他の方々は脱落されましたのでこれからは一人ずつ排除されます！では、ご記入のご準備よろしいですか？」" },
        { type: "choice", image: "test.png", name: "たぬき", text: "（んん...多分混乱させるか、逃げるか、追加するかだから...どれだ？）", choices: [{ text: "混乱させる", jump: "atamaguruguru" }, { text: "逃げる", jump: "overj" }, { text: "追加する", jump: "overj" }] },
        { label: "overj" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "「結果を発表いたします。アンドロイド0006、0004、0003様は正解おめでとうございます！！」" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "「結果を発表いたします。アンドロイド0006、0004、0003様は正解おめでとうございます！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（えっ？ぼくは？）" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "「たぬき様は不正解です。よって地縛霊に変換いたします。」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（ぼくは間違ってしまったのか...。しょうがないおとなしく地縛霊に変換されるか...。自分の間違いだからな...。）" },
        { type: "message1", image: "test.png", name: "？？", text: "ヒューン ドン" },
        { type: "message1", image: "test.png", name: "たぬき", text: "なっなんだ上のほうにポツンとあかりが！あんなとこから落ちてきたんだ..." },
        { type: "message1", image: "test.png", name: "？？？", text: "そこのお前早くドアに入れ！" },
        { type: "message1", image: "test.png", name: "？？", text: "ドン" },
        { type: "choice", image: "test.png", name: "たぬき", text: "わーーー...", choices: [{ text: "さっきの人は誰？", jump: "overjibakurei" }] },
        { label: "atamaguruguru" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "「皆さまご正解おめでとうございます！皆さまには次の問題に進む資格があります！」" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "「なので次の問題は.....　その前に席についてください！」\n「では改めて.....。」" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "「第2問！！」デレーン\n「虫は虫でも歯についている虫は？」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "え？今度はなぞなぞ？まあさっきよりは簡単か...っと前にボタンを押して...　ピンポン　ピンポン" },
        { type: "gameClear", image: "test.png", name: "たぬき", text: "ぎっ　ぎりぎりじゃん💦アンドロイドはやっ！！まっまあそれはおいといて...虫は虫でも歯についてる虫だから...虫歯のような気がするけど...ひっかけでいつもの虫な可能性もあるし...どっちだ！？" },//, choices: [{ text: "虫歯", jump: "musiba" }, { text: "いつもの虫", jump: "overmusi" }] },


        //上まだ
        { label: "curse" },
        { type: "message1", image: "test.png", name: "解説", text: "呪うを選択した！\n目の前にドアが現れた！？" },
        { type: "message1", image: "test.png", name: "たぬき", text: "行き先は...　[style='text-decoration:underline;']じごく！？]" },
        { type: "message1", image: "test.png", name: "たぬき", text: "どどどどどどどどうしよう！？\nでも、まわりにはなにもないし、「呪う」を選択しちゃったからしょうがないよね？" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし！思いっきり入ってみよう！！" },
        { type: "message1", image: "black.png", name: "解説", text: "さあ、たぬきはどうなる！？" },
        { type: "message1", image: "test.png", name: "風の音", text: "༄　ヒュー" },
        { type: "message1", image: "test.png", name: "たぬき", text: "えっ　ここは...\n\nじごくだぁーーーーーーーーー！！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "えんま大王が審査を行っている！！" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "「おいっ　そこのたぬき！！」" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "「お前はこのままじごくに残るか天国へ行くかどっちがいいか！？」" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "「答えろ！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "ひぃーーー💦\n天国に行きたいけどいやな予感がするから、じごくに残ろう！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「じっじごくに残ります」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（あっ）やばい声が小さくなりすぎた！" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "「あー！？」\n「なんだって！？聞こえねえぞ！！」" },
        { type: "choice", image: "test.png", name: "たぬき", text: "もっもう一回！？　（天国に行きたいなぁ...）なにこの気持ち！？もうっ！決めたんだ！！\nでっでも行きたいかも...", choices: [{ text: "天国に行く", jump: "over1" }, { text: "地獄に残る", jump: "jigoku" }] },
        { label: "over1" },
        { type: "message1", image: "oni.png", name: "鬼たち", text: "「ヴァッカモーーーン！！」" },
        { type: "message1", image: "oni.png", name: "たぬき", text: "「！？」\nいつからいたのか、鬼が5匹、ぼくのまわりをかこんでいる！" },
        { type: "message1", image: "oni.png", name: "たぬき", text: "そして、こん棒と銃で殺そうとしているんだ...　今度こそ死んでしまう！！\n「やっやめて！！」" },
        { type: "message1", image: "oni.png", name: "鬼たち", text: "「問答無用！！」" },
        { type: "gameOver", image: "black.png", name: "？？", text: "[style='font-weight:bold;font-size:40px;']パーン！！]" },
        { label: "jigoku" },
        { type: "choice", image: "test.png", name: "なぞの生物", text: "「君は、他の皆と違って少し、頭がよさそうだな！！\nそれだけにおしい...　ここからは、じごくを冒険してもらう。全てのじごくをクリアしたら、天国へいけ！！」", choices: [{ text: "始める", jump: "jigoku1" }] },
        { label: "jigoku1" },
        { type: "message1", image: "test.png", name: "なぞの生物", text: "「最初は、針山じごくだ。さあ、ルール説明は次だ」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下", text: "「ルール説明で頭がこんがらないように、気を付けるんだな！！」「じゃあ始める！！」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下", text: "「あーしてこーして　まあいい！！はりやまじごくをクリアしたら矢印がさす方向に進んで　\n一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一\n一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（はっはや！？最初しか聞き取れなかった...）" },
        { type: "message1", image: "test.png", name: "えんま大王の手下", text: "「[style='font-weight:bold;font-size:40px;']いいな？]」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（え、何？一切わからないけハイって答えるしかないよね？）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ハ、ハイッ！」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下", text: "「じゃ、ファイト！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（え、もうやっていいってこと？\nえーいどうでもいい　やるぞ！）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ん？」\nげたがある！これをはけってことか..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし、じゃあ改めてやるぞ！" },
        { type: "message1", image: "test.png", name: "？？", text: "ボキッボキボキボキ" },
        { type: "choice", image: "test.png", name: "たぬき", text: "何この音？まさかげたが壊れる音！！？\nもう半分くらいまで来たけど引き返そうかな？", choices: [{ text: "引き返す", jump: "hariyamagoal" }, { text: "進む", jump: "over2" }] },
        { label: "over2" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ギャアアアアアアアアアアア...___________________________！！」" },
        { type: "gameOver", image: "black.png", name: "解説", text: "背中に強いしょうげきが走ったと同時にたぬきの意識はなくなった。その時たぬきは何が起こったのか確信した。" },
        { label: "hariyamagoal" },
        { type: "message1", image: "test.png", name: "たぬき", text: "引き返して正解だった。\n「ん？」げたのとなりにせおえるカゴが置いてあるぞ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "これの中にげたを入れてせおうのか！これで進めるぞ！" },
        { type: "message1", image: "test.png", name: "？？", text: "バキッ" },
        { type: "message1", image: "test.png", name: "たぬき", text: "折れそう！でも新しいげたを取り出せば！" },
        { type: "message1", image: "white.png", name: "解説", text: "これを何回かくり返し..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "最後にジャンプしてゴール！" },
        { type: "choice", image: "test.png", name: "えんま大王の手下", text: "「なかなかやるじゃないか」「次へ行け」", choices: [{ text: "次へ行く", jump: "huttou" }] },
        { label: "huttou" },
        { type: "message1", image: "test.png", name: "えんま大王の手下2", text: "「今回はふっとうじごくだ」「そこのでかいなべの中に入って五分間もちこたえればいい\nとちゅうで熱くなったら出ていいが、もし出てしまったら...針山じごくからやり直せ！！」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下2", text: "「ルール説明はここまでだ。あとこのコインをくれてやる」「そこの列にならべ！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（なんかさっきの鬼よりこわすぎるんですけど）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "まあ列にならぶか...ならんでと...ふーん一回に十人入るのか！それにしても出たら一からか...\nまあがんばるぞ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし！！ぼくの番だ！相変わらずじごくの鬼はらんぼうだな...（まあ例外もいるけど...）" },
        { type: "message1", image: "test.png", name: "？？", text: "ドンッ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（キャーー）声にならない声！！あっつーーーーーー！！！！" },
        { type: "choice", image: "test.png", name: "たぬき", text: "こんなに熱いの知らないよ！！助けて！もう出たい！でも一からだし...", choices: [{ text: "でる", jump: "loop" }, { text: "泳ぐ", jump: "swim" }, { text: "でない", jump: "over3" }] },
        { label: "over3" },
        { type: "message1", image: "test.png", name: "たぬき", text: "クッもう無理だ...\nぼくは、ここで死んでしまうんだ..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "選択を違うのにすればよかった..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "今ごろ後悔しても...おそい...か..." },
        { type: "gameOver", image: "test.png", name: "解説", text: "たぬきの意識はなくなった..." },
        { label: "loop" },
        { type: "message1", image: "test.png", name: "たぬき", text: "出るぞ！でもどうやって出るんだ？\n鬼さんに聞いてみるか！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「おっおおおおにさんどどどどうやってでるんですか？」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下3", text: "「ん？」「あぁでるんだな☺\nそこのはしごで登って、矢印の方向に進むと、針山じごくに行ける！！がんばれよ！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（？やさしっ！？）（この鬼好きかも！！こんなにじごくにきた人にやさしい人はいない！？　まさかかくしごとがあるのかも？）\n（まぁいいや！）\n「よしっ」はしご登ってやるぞ！" },
        { type: "choice", image: "test.png", name: "たぬき", text: "　", choices: [{ text: "矢印についていく", jump: "jigoku1" }] },
        { label: "swim" },
        { type: "message1", image: "test.png", name: "たぬき", text: "クッ　ももう無理だでも　お泳ぐぞ！！\n犬かきだぁーー！！バチャバチャバチャバチャ　意外と熱くないぞ！！" },
        { type: "message1", image: "test.png", name: "えんま大王の手下3", text: "「おいおい君」「もう五分たったよ」" },
        { type: "cimg", key: "r", image: "test.png", image2: "test.png  ", name: "たぬき", text: "（えっ！？）「よっしゃーーーーーーーーー！！」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下3", text: "「うっさい！」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下3", text: "「まあがんばったな！次もがんばれよ　はしごを登って矢印の方向へ行けばいい」" },
        { type: "message1", image: "test.png", name: "えんま大王の手下3", text: "「健闘を祈るぜ！」" },
        { type: "message1", image: "test.png", name: "（たぬきによると進化してるらしい）AI", text: "「ふんっ　ようやくこれたようだな...」" },
        { type: "message1", image: "test.png", name: "AI", text: "「次の地獄は洗濯物干し地獄だ　一日に1000枚洋服を干してもらう。ルールは一度しか言わないぞ。（洗濯物干しとか考えることが子どｍうわ何をするやめろくぁwせdrftgyふじこlp）」" },
        { type: "message1", image: "test.png", name: "AI", text: "「ルールは、\n（ルール説明中）\nだ。いいな。わかったら次へ進め」" },
        { type: "message1", image: "test.png", name: "アンドロイド", text: "「スリープモードカイジョ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（え？）" },
        { type: "message1", image: "test.png", name: "アンドロイド", text: "「R0762キドウシマス　タイショウカクニンチュウ... 」" },
        { type: "message1", image: "test.png", name: "アンドロイドR0762", text: "「タイショウカクニン　ゲートロックカイジョ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（ど、どゆこと？）" },
        { type: "message1", image: "test.png", name: "アンドロイドR0762", text: "「タヌキサマ　サキニオススミクダサイ」" },
        { type: "message1", image: "test.png", name: "アンドロイドR0762", text: "「ニュウジョウカクニンカンリョウ」" },
        { type: "message1", image: "test.png", name: "アンドロイドR0762", text: "「ゲートロックチュウ...　ゲートロックカンリョウシマシタ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（！？）" },
        { type: "message1", image: "test.png", name: "アンドロイドR0762", text: "「モウアトモドリハデキナイ、死ノセカイヲタノシンデ...」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（まあ、とりあえず行くか...）" },
        { type: "message1", image: "test.png", name: "アンドロイド", text: "「コンニチハ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「だっだれ！？またアンドロイド！？」" },
        { type: "message1", image: "test.png", name: "アンドロイドR0763", text: "「オット　モウシオクレマシタ　ワタシハアンドロイドノNO.0763デス　ココデハルールドオリノコトヲスレバゴウカク、シナケレバ...　ハイジョサレマス」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（いきなりこわっ！？）" },
        { type: "message1", image: "test.png", name: "アンドロイドR0763", text: "「フフフ...　デモトニカクホスダケ、スピードトハンシャシンケイガジュウヨウデス」" },
        { type: "message1", image: "test.png", name: "アンドロイドR0763", text: "「ソレデハガンバッテーー」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "現場はどうなっているのかな？（え？）みーんなアンドロイド！勝てっこないよ～！" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "ピンポンパンポーン＜＜カイシ10ビョウマエ　10, 9, ...＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "やべっ\n位置について..." },
        { type: "message1", image: "test.png", name: "アナウンス", text: "＜＜3, 2, 1... シンサカイシ＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "うおー！！干して干して干して干しまくるー！！！" },
        { type: "message1", image: "test.png", name: "久々の解説", text: "（6時間がたち...）" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "＜＜シュウリョウ2ジカンマエ... 1ジカン59フン...＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "まだまだじゃねえか！！うおおおおおおおおお！！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "おぉぉーーーーーー！！おぉーーーーーー！！　干して、干して、干しまくる！" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "＜＜アト30プンデス... ＞＞（しばらくして...）＜＜アト10プンデス...＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（えぇーー！？）" },
        { type: "message1", image: "test.png", name: "アナウンス", text: "＜＜ノコリ　30ビョウ...＞＞\n＜＜シンサシュウリョウ＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "え、もう終わっちゃったの？？あと一枚残ってるんだけど...！？" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「ソコノタヌキ　スベテ　ホシオワッタカ？？」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "えっと、えっと...（言うしかないよね！？）「い、い、一枚残ってままますすす。」" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「ソウ、ザンネン...。」" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "ピーピー　「タイショウ　ハイジョヲ　ハジメマス」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "ええええ...！！！！　なんで！？" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「サイショニセツメイシタハズデス　ワタシハアンドロイド　メイレイサレタコトハジッコウシマス　デハサヨウナラ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "やばいやばい！！今度こそ、し、死ぬ！！！", choices: [{ text: "水をかける", jump: "mizu" }, { text: "対戦する", jump: "overbattle" }] },
        { label: "overbattle" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よしっ！！対戦するぞ！！何か使えるモノ..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "あ！ハンガー発見！コレをこうして..." },
        { type: "message1", image: "test.png", name: "たぬき", text: "できた！名付けて...ハンガーストロング砲！" },
        { type: "message1", image: "test.png", name: "解説", text: "（説明しよう！こうやってハンガーを引っ張ると発射されるのだ！）" },
        { type: "message1", image: "test.png", name: "たぬき", text: "ってことで...「アンドロイド！戦うぞ！」" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「エ・・・？マアイイカ...　シカシ、ワタシハムテキノアンドロイド　キミニハカナワナイヨ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "それでも！！" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「アア、ワカッタ、イットクケドワタシハ　ケイコクシタシ　ウチノメサレテモジブンノセイダ　イイネ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ああ、最高の決闘を始めようじゃないか」（あ、言っちゃった...）" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「ザンネンダ　マアオマエナンテイチコロダガナ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よし、攻撃開始！まずは瞬間移動で相手を翻弄！" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「？？？」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（よし、成功！？）" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「コウゲキジュンビカイシ」「ピ————————」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（あ）で、でもこのハンガーストロング砲がある！\n引っ張ってーーーっ　飛んだ！！" },
        { type: "message1", image: "test.png", name: "？？", text: "「バリバリ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "よっしゃ顔面にヒット！" },
        { type: "message1", image: "test.png", name: "？？", text: "＜＜ウーウー　 非常事態発生アンドロイドが破壊されました　これよりアンドロイド、[style='text-decoration:line-through;']粛清]破壊モードを発動＞＞" },
        { type: "message1", image: "test.png", name: "たぬき", text: "え？終わった..." },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「ハカイコウウセン　ホウシュツジュンビ　ホウシュツ5ビョウマエ　5, 4, 3, ...」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "やばい！どうすれば！" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「3, 2, 1, ... シュクセイ」" },
        { type: "message1", image: "test.png", name: "？？", text: "[style='font-size:50px;']ドカーン]" },
        { type: "message1", image: "test.png", name: "解説", text: "アンドロイドの破壊光線が放出されたと同時にたぬきは飛ばされた。\n頭が「何か」当たった瞬間、彼の中のすべては消えた。" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「ハア、ダカラケイコクシタノニ...」" },
        { type: "message1", image: "test.png", name: "解説", text: "ぐちゃぐちゃになった顔面でアンドロイドは言った。" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「...コレデマタヒトリギセイニナッタ... フフ、アッハッハッハッハー！！」" },
        { type: "gameOver", image: "test.png", name: "重々しいナレーション", text: "アンドロイドにけんかなんて売らなければよかったのに。\nまあ、もう遅いか。" },
        { label: "mizu" },
        { type: "message1", image: "test.png", name: "たぬき", text: "水をかけるぞ！あ！あそこに井戸とバケツが！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「おーい！ちょっと来いよー！」（バケツを後ろに念のため2個隠して）" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「ミズカラコロサレニクルトハ、バカナコダヌキダ...」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「殺されるのは...どっちだろうな！！」" },
        { type: "message1", image: "test.png", name: "？？", text: "バシャアアン" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「！？」「ナ...ナンデ...」　バチッ　「ウウ、アアアバ、バカナ！ワタシハサイキョウノアンドロイド、ココデシヌハズガナイ！！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「どの口が言ってんだよ！もういっちょ！あばよ！」" },
        { type: "message1", image: "test.png", name: "？？", text: "バッシャアアアン" },
        { type: "message1", image: "test.png", name: "アンドロイドR0764", text: "「ウアアアアアアアアアア...」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「よっしゃああ　勝ったぞー！」で、どうすれば？" },
        { type: "message1", image: "test.png", name: "AI", text: "「よくやった、これで次に進むゲートが開いた。先に進んでくれ。」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「おおAI！どこにあるの？」" },
        { type: "message1", image: "test.png", name: "AI", text: "「すぐ出てくるはずだ」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "（ブツ）出てきた！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「で、次は何の試練？」" },
        { type: "message1", image: "test.png", name: "AI", text: "「おっと、それはゲートに入ってから聞いてくれ、それでは、アデュー！」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "じゃ、ゲート入るか...（ウィーン）おお！あいた！じゃあ入るぞ！Let's go!" },
        { type: "message1", image: "white.png", name: "たぬき", text: "？？？　どこかに飛ばされたぞ！？" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "おめでとう！ここまでこれたのは君が最初だ！\nここではおれさまの手下を100人倒したらクリアだ。おれさまの手下は分身するから気をつけろ！" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「あっあの。」" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "「ああ？」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「そんなにたくさんの手下を使ってすべて倒されてしまった場合　えんま様はお困りになられないのでしょうか？？」" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "「大丈夫だ。おれさまには、手下を量産できるとっておきの機械があるからな。あと、おれさまのことは、えんま大王様とよべ！わかったか？」" },
        { type: "message1", image: "test.png", name: "たぬき", text: "「ハッハイ！！」" },
        { type: "message1", image: "test.png", name: "えんま大王", text: "「OK！細かい説明は次だ。」「邪魔だからさっさといけ！！」" },
        { type: "gameClear", image: "test.png", name: "開発者", text: "ここまでしかつくってないよーん" },
    ];
};

